# Generated by Django 2.2.1 on 2021-12-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Commentt')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('U', 'User'), ('A', 'Admin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=300)),
                ('pub_date', models.DateTimeField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
                ('resources', models.ManyToManyField(to='firstApp.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(to='firstApp.Tag'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(max_length=600)),
                ('whoAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoAnswer', to='firstApp.Person')),
                ('whoAsk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoAsk', to='firstApp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, null=True, to='firstApp.Resource'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notiftype', models.CharField(choices=[('CR', 'commentReply'), ('LC', 'likeComment')], max_length=2)),
                ('commentReply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.Commentt')),
                ('likecomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.LikeComment')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='firstApp.Person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='firstApp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='likecomment',
            name='pers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
                ('resc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='commentt',
            name='pers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person'),
        ),
        migrations.AddField(
            model_name='commentt',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.Commentt'),
        ),
        migrations.AddField(
            model_name='commentt',
            name='resc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Resource'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
            ],
        ),
    ]
