# Generated by Django 2.2.1 on 2021-12-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
