# Generated by Django 2.2.1 on 2021-12-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
