# Generated by Django 3.2.9 on 2021-12-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_resource_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.person')),
                ('resc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.resource')),
            ],
        ),
        migrations.CreateModel(
            name='QualifiedInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.person')),
                ('resc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.resource')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.person')),
                ('resc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.resource')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDepthAndCovergae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.person')),
                ('resc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ContentQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.person')),
                ('resc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.resource')),
            ],
        ),
    ]
