# Generated by Django 3.2.9 on 2021-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_contentquality_coursedepthandcovergae_coursepace_qualifiedinstructor_videoquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
