# Generated by Django 2.2.1 on 2021-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0011_auto_20211220_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
