# Generated by Django 3.2.9 on 2021-12-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_alter_resource_image'),
        ('firstApp', '0012_auto_20211220_1026'),
    ]

    operations = [
    ]
