# Generated by Django 2.2.1 on 2021-12-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_merge_20211220_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='resources',
        ),
        migrations.AddField(
            model_name='resource',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, to='firstApp.Subcategory'),
        ),
    ]
