# Generated by Django 2.2.1 on 2021-12-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0015_auto_20211221_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
