# Generated by Django 2.2.1 on 2022-01-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0017_auto_20211226_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Commentt')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
            ],
        ),
    ]
